# Generated by Django 2.1.7 on 2019-03-27 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_to_person', models.CharField(max_length=50)),
                ('related_to_place', models.CharField(max_length=100)),
                ('activity_note', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted')], default='uncompleted', max_length=20)),
            ],
        ),
    ]
